// src/components/SetAlarmModal.vue
<template>
    <div class="set-time-modal">
        <div class="background" @click="closeModal"></div>

        <div class="content">

            <img class="content-x-btn" src="../../public/img/icon/x-icon.svg" @click="closeModal">

            <div class="modal-title">알람설정</div>
            <div class="bar"></div>

            <div class="content-box">
                <div class="content-item-box">
                    <div class="content-item-title">시간선택</div>
                    <div style="display: flex; flex: 1">
                        <select class="select-am-pm" v-model="amPm">
                            <option>오전</option>
                            <option>오후</option>
                        </select>
         
                        <div class="content-time-box" style="margin-right: 7px;">
                            <select class="select-time" v-model="hour">
                                <option>00</option>
                                <option>01</option>
                                <option>02</option>
                                <option>03</option>
                                <option>04</option>
                                <option>05</option>
                                <option>06</option>
                                <option>07</option>
                                <option>08</option>
                                <option>09</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                            </select>
                            <div>시</div>
                        </div>
                        <div class="content-time-box">
                            <select class="select-time" v-model="minute">
                                <option>00</option>
                                <option>01</option>
                                <option>02</option>
                                <option>03</option>
                                <option>04</option>
                                <option>05</option>
                                <option>06</option>
                                <option>07</option>
                                <option>08</option>
                                <option>09</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                                <option>17</option>
                                <option>18</option>
                                <option>19</option>
                                <option>20</option>
                                <option>21</option>
                                <option>22</option>
                                <option>23</option>
                                <option>24</option>
                                <option>25</option>
                                <option>26</option>
                                <option>27</option>
                                <option>28</option>
                                <option>29</option>
                                <option>30</option>
                                <option>31</option>
                                <option>32</option>
                                <option>33</option>
                                <option>34</option>
                                <option>35</option>
                                <option>36</option>
                                <option>37</option>
                                <option>38</option>
                                <option>39</option>
                                <option>40</option>
                                <option>41</option>
                                <option>42</option>
                                <option>43</option>
                                <option>44</option>
                                <option>45</option>
                                <option>46</option>
                                <option>47</option>
                                <option>48</option>
                                <option>49</option>
                                <option>50</option>
                                <option>51</option>
                                <option>52</option>
                                <option>53</option>
                                <option>54</option>
                                <option>55</option>
                                <option>56</option>
                                <option>57</option>
                                <option>58</option>
                                <option>59</option>
                            </select>
                            <div>분</div>
                        </div>
                    </div>
                </div>

                <div class="content-item-box">
                    <div class="content-item-title">알림음</div>
                    <div style="display: flex; flex: 1; align-items: center; justify-content: space-between">
                        <select class="select-alarm-music" v-model="alarmMusic">
                            <option>새소리</option>
                        </select>

                        <div style="display: flex; gap: 2px; margin: 0 auto 0 8px;">
                            <div class="icon-box">
                                <img style="margin-left: 3px;" src="../../public/img/icon/play-icon.svg">
                            </div>

                            <div class="icon-box">
                                <img style="margin-left: 1px;" src="../../public/img/icon/upload-icon.svg">
                            </div>
                        </div>

                        <div class="repeat-box">
                            <div class="check-icon-box">
                                <img src="../../public/img/icon/check-0-icon.svg">
                            </div>
                            <div>반복재생</div>
                        </div>
                    </div>
                </div>

                <div class="content-item-box">
                    <div class="content-item-title">알람이름</div>
                    <input class="input-alarm-name" placeholder="알람 이름을 입력하세요." v-model="alarmName">
                </div>

            </div>

            <div class="content-btn-box">
                <div class="modal-cancel" @click="closeModal">취소</div>
                <div class="modal-add-alarm-btn" @click="settingAlarm">설정하기</div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { defineEmits, onMounted, ref } from "vue";

const amPm = ref('오전');
const hour = ref('00');
const minute = ref('00');
const alarmMusic = ref('새소리');
const alarmName = ref('');

const emit = defineEmits([
  'setAlarm',
  'closeSetAlarmModal'
]);

const closeModal = () => {
    emit('closeSetAlarmModal');
}

const settingAlarm = () => {
    emit('setAlarm', {
        amPm: amPm.value,
        hour: hour.value,
        minute: minute.value,
        alarmMusic: alarmMusic.value,
        alarmName: alarmName.value,
        fullTime: amPm.value === '오전' ?
         hour.value + '-' + minute.value
         : String(Number(hour.value) + 12) + '-' + minute.value
    });
}

onMounted(() => {

})

</script>
  
<style>
.set-time-modal {
    position: fixed;
}

.background {
    z-index: 100;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: var(--modal-bg-color-1);
}

.content {
    z-index: 100;
    position: fixed;
    max-width: 688px;
    width: 70%;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: var(--bg-color-2);
    border-radius: 8px;

    padding: 0 23px;
}

.content-x-btn {
    position: absolute;
    top: 16px;
    right: 25px;
    cursor: pointer;
}

.modal-title {
    text-align: center;
    margin: 29px 0 10px 0;
    font-weight: 700;
    color: var(--text-color-2);
    font-size: 14px;
}

.bar {
    border-bottom: 1px solid var(--border-color-2);
}

.content-box {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;
    margin: 30px 0 22px 0;
    padding: 0 70px;
}


.content-item-box {
    display: flex;
    width: 100%;
    align-items: center;
}


.select-am-pm {
    width: 82px;
    height: 28px;
    text-align: center;
    border-radius: 500px;
    margin-right: auto;
    font-size: 12px;
    border: 0.5px solid var(--border-color-2);
    color: #242627;
    background-color: var(--bg-color-7);
}

.select-time {
    width: 113px;
    height: 28px;
    text-align: center;
    border-radius: 500px;
    font-size: 12px;
    border: 0.5px solid var(--border-color-2);
    color: #242627;
    background-color: var(--bg-color-7);
}


.content-time-box {
    display: flex;
    align-items: center;
    color: var(--text-color-1);
    font-size: 14px;
    gap: 5px;
}

.content-item-title {
    width: 95px;
    font-size: 12px;
    color: var(--text-color-1);
}

.select-alarm-music {
    width: 217px;
    height: 28px;
    border-radius: 500px;
    box-sizing: border-box;
    font-size: 12px;
    padding: 0 16px;
    border: 0.5px solid var(--border-color-2);
    color: #242627;
    background-color: var(--bg-color-7);
}

.icon-box {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 28px;
    height: 28px;
    border: 0.5px solid var(--border-color-2);
    border-radius: 50%;
    cursor: pointer;
}

.icon-box:hover {
    background-color: #eeeeee;
}

.check-icon-box {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 18px;
    height: 18px;
    border: 0.5px solid var(--border-color-2);
    border-radius: 50%;
    cursor: pointer;
}

.check-icon-box:hover { 
    background-color: #eeeeee;
}

.repeat-box {
    display: flex;
    gap: 5px; 
    align-items: center;
    font-size: 12px;
    color: var(--text-color-1);
}



.input-alarm-name {
    height: 28px;
    flex: 1;
    border-radius: 500px;
    box-sizing: border-box;
    font-size: 10px;
    border: 0.5px solid var(--border-color-2);
    padding: 0 18px;
}


.content-btn-box {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 16px;
    margin-bottom: 30px;
}

.modal-cancel {
    cursor: pointer;
    font-size: 12px;
    color: var(--text-color-1);
}

.modal-add-alarm-btn {
    display: flex;
    justify-content: center;
    align-items: center;
    color: white;
    background-color: var(--bg-color-4);
    width: 83px;
    height: 28px;
    border-radius: 500px;
    font-weight: 700;
    font-size: 12px;
    cursor: pointer;
}


.modal-add-alarm-btn:hover {
    background-color: var(--bg-hover-color-1);
}
</style>

// components/modals/SetAlarmModal.tsx
'use client';

import { useState } from 'react';
import { Alarm } from '@/lib/types';

interface SetAlarmModalProps {
  onClose: () => void;
  onSave: (alarm: Omit<Alarm, 'id' | 'createdAt'>) => void;
  editAlarm?: Alarm | null;
}

export default function SetAlarmModal({ onClose, onSave, editAlarm }: SetAlarmModalProps) {
  const [amPm, setAmPm] = useState(editAlarm?.amPm || '오전');
  const [hour, setHour] = useState(editAlarm?.hour || '07');
  const [minute, setMinute] = useState(editAlarm?.minute || '00');
  const [alarmName, setAlarmName] = useState(editAlarm?.alarmName || '');
  const [alarmMusic, setAlarmMusic] = useState(editAlarm?.alarmMusic || '새소리');
  const [repeat, setRepeat] = useState<string[]>(editAlarm?.repeat || []);

  const hours = Array.from({ length: 12 }, (_, i) => String(i + 1).padStart(2, '0'));
  const minutes = Array.from({ length: 60 }, (_, i) => String(i).padStart(2, '0'));

  const weekDays = [
    { key: '월', label: '월' },
    { key: '화', label: '화' },
    { key: '수', label: '수' },
    { key: '목', label: '목' },
    { key: '금', label: '금' },
    { key: '토', label: '토' },
    { key: '일', label: '일' },
  ];

  const toggleRepeat = (day: string) => {
    setRepeat((prev) =>
      prev.includes(day) ? prev.filter((d) => d !== day) : [...prev, day]
    );
  };

  const handleSave = () => {
    const hourNum = parseInt(hour);
    const fullTime = amPm === '오전'
      ? `${hourNum === 12 ? 0 : hourNum}:${minute}`
      : `${hourNum === 12 ? 12 : hourNum + 12}:${minute}`;

    onSave({
      amPm,
      hour,
      minute,
      alarmName,
      alarmMusic,
      fullTime,
      enabled: true,
      repeat,
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div
        className="absolute inset-0 bg-[var(--modal-bg-color-1)] backdrop-blur-sm"
        onClick={onClose}
      />
      <div className="relative bg-[var(--bg-color-2)] rounded-2xl shadow-2xl w-[95%] sm:w-[90%] max-w-2xl p-4 sm:p-6 animate-fade-in-up">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[var(--bg-color-1)] transition-colors"
        >
          ✕
        </button>

        <h2 className="text-lg sm:text-xl font-bold text-center mb-4 sm:mb-6 text-[var(--text-color-1)]">
          {editAlarm ? '알람 수정' : '알람 설정'}
        </h2>

        <div className="space-y-4 sm:space-y-6">
          {/* 시간 선택 */}
          <div className="flex items-center gap-3 sm:gap-4">
            <label className="w-24 text-sm font-medium text-[var(--text-color-1)]">
              시간 선택
            </label>
            <div className="flex-1 flex gap-2 sm:gap-3">
              <select
                value={amPm}
                onChange={(e) => setAmPm(e.target.value)}
                className="px-3 sm:px-4 py-2 rounded-full border border-[var(--border-color-2)] bg-[var(--bg-color-7)] text-[var(--text-color-1)] text-sm sm:text-base cursor-pointer focus:outline-none focus:ring-2 focus:ring-[var(--bg-color-4)]"
              >
                <option>오전</option>
                <option>오후</option>
              </select>

              <select
                value={hour}
                onChange={(e) => setHour(e.target.value)}
                className="px-3 sm:px-4 py-2 rounded-full border border-[var(--border-color-2)] bg-[var(--bg-color-7)] text-[var(--text-color-1)] text-sm sm:text-base cursor-pointer focus:outline-none focus:ring-2 focus:ring-[var(--bg-color-4)]"
              >
                {hours.map((h) => (
                  <option key={h} value={h}>
                    {h}시
                  </option>
                ))}
              </select>

              <select
                value={minute}
                onChange={(e) => setMinute(e.target.value)}
                className="px-3 sm:px-4 py-2 rounded-full border border-[var(--border-color-2)] bg-[var(--bg-color-7)] text-[var(--text-color-1)] text-sm sm:text-base cursor-pointer focus:outline-none focus:ring-2 focus:ring-[var(--bg-color-4)]"
              >
                {minutes.map((m) => (
                  <option key={m} value={m}>
                    {m}분
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* 반복 */}
          <div className="flex items-start gap-3 sm:gap-4">
            <label className="w-24 text-sm font-medium text-[var(--text-color-1)] pt-2">
              반복
            </label>
            <div className="flex-1 flex gap-2 flex-wrap">
              {weekDays.map(({ key, label }) => (
                <button
                  key={key}
                  onClick={() => toggleRepeat(key)}
                  className={`w-10 h-10 rounded-full font-semibold transition-all duration-300 ${
                    repeat.includes(key)
                      ? 'bg-[var(--bg-color-4)] text-white'
                      : 'bg-[var(--bg-color-1)] text-[var(--text-color-2)] hover:bg-[var(--bg-color-3)]'
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          {/* 알람 이름 */}
          <div className="flex items-center gap-3 sm:gap-4">
            <label className="w-24 text-sm font-medium text-[var(--text-color-1)]">
              알람 이름
            </label>
            <input
              type="text"
              value={alarmName}
              onChange={(e) => setAlarmName(e.target.value)}
              placeholder="알람 이름을 입력하세요"
              className="flex-1 px-3 sm:px-4 py-2 rounded-full border border-[var(--border-color-2)] bg-[var(--bg-color-7)] text-[var(--text-color-1)] text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-[var(--bg-color-4)]"
            />
          </div>

          {/* 알림음 */}
          <div className="flex items-center gap-3 sm:gap-4">
            <label className="w-24 text-sm font-medium text-[var(--text-color-1)]">
              알림음
            </label>
            <select
              value={alarmMusic}
              onChange={(e) => setAlarmMusic(e.target.value)}
              className="flex-1 px-3 sm:px-4 py-2 rounded-full border border-[var(--border-color-2)] bg-[var(--bg-color-7)] text-[var(--text-color-1)] text-sm sm:text-base cursor-pointer focus:outline-none focus:ring-2 focus:ring-[var(--bg-color-4)]"
            >
              <option>새소리</option>
              <option>벨소리</option>
              <option>차임벨</option>
              <option>기타</option>
            </select>
          </div>
        </div>

        {/* 버튼 */}
        <div className="flex gap-2 sm:gap-3 justify-center mt-6 sm:mt-8">
          <button
            onClick={onClose}
            className="px-4 sm:px-6 py-2.5 rounded-full text-[var(--text-color-1)] text-sm sm:text-base hover:bg-[var(--bg-color-1)] transition-colors"
          >
            취소
          </button>
          <button
            onClick={handleSave}
            className="px-5 sm:px-8 py-2.5 bg-gradient-to-r from-[var(--bg-color-4)] to-[var(--bg-color-6)] text-white rounded-full font-semibold text-sm sm:text-base shadow-lg transition-all duration-300 hover:-translate-y-0.5 hover:shadow-xl"
          >
            {editAlarm ? '수정하기' : '설정하기'}
          </button>
        </div>
      </div>
    </div>
  );
}
